[versions]
junit = "5.10.0"
guava = "32.1.3-jre"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }

[bundles]
test = ["junit-jupiter"]
